### ISSUE TITLE
Allow to wait some time before timeouting initial connection to the database

### ISSUE THREAD

**Issue by onnimonni** [humanmade/Cavalcade-Runner#34]
I'm running this in local docker environment and I'm hitting an error which says that database refuses connection:
```
web_1       | worker.1  | Error: SQLSTATE[HY000] [2002] Connection refused
web_1       | worker.1  | #0 /var/www/project/vendor/humanmade/cavalcade-runner/lib/Runner.php(200): PDO->__construct('mysql:host=mysq...', 'web', 'password', Array)
web_1       | worker.1  | #1 /var/www/project/vendor/humanmade/cavalcade-runner/lib/Runner.php(89): HM\Cavalcade\Runner\Runner->connect_to_db()
web_1       | worker.1  | #2 /var/www/project/vendor/humanmade/cavalcade-runner/bin/cavalcade(26): HM\Cavalcade\Runner\Runner->bootstrap('/var/www/projec...')
web_1       | worker.1  | #3 {main}
```
This happens because my mysql is not ready yet. Could we add a default timeout which could be adjusted with an flag like `--timeout=10`?

**Comment by rmccue** [comment]
Why not build the timeout into your script running Cavalcade Runner instead? (`sleep 10 && cavalcade`) It seems like a system-specific thing if your MySQL instance hasn't yet started, rather than something specific to Cavalcade.

**Comment by onnimonni** [comment]
I think it would be better to have it in cavalcade itself so it can also automatically retry few times before failing. There must be other environments where this is preferable default behaviour too.
